// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://eqzbyepcdrc2bfrgf4k2x2pmly.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aeww5mc4k5gaba3n5m3ibu2xee",
    "aws_cognito_identity_pool_id": "us-east-1:0bbfedce-202b-44a0-b398-4c90c24d541b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Xjub49Em7",
    "aws_user_pools_web_client_id": "4d71touquld4hl0ife48iam33u",
    "oauth": {}
};


export default awsmobile;
